export { classesApi } from "./classes.api";
export { teachersApi } from "./teachers.api";
export { subjectsApi } from "./subjects.api";
export { studentsApi } from "./students.api";
export { teacherSubjectsApi } from "./teacherSubjects.api";
export { classSubjectsApi } from "./classSubjects.api";
export { examsApi } from "./exams.api";
export { resultsApi } from "./results.api";
export { authApi } from "./auth.api";
